---
- name: set internal variable platform-suffix for convenience
  set_fact:
    prometheus_platform_suffix: "linux-amd64"
  when: ansible_architecture == "x86_64"

- name: set internal variable platform-suffix for convenience
  set_fact:
    prometheus_platform_suffix: "linux-armv7"
  when: ansible_architecture == "armv7l"

- name: set internal variables for convenience
  set_fact:
    prometheus_blackbox_exporter_subdir: "{{ prometheus_blackbox_exporter_install_path }}/blackbox_exporter-{{ prometheus_blackbox_exporter_version }}.{{ prometheus_platform_suffix }}"  # noqa 204

- name: set internal variables for convenience
  set_fact:
    prometheus_blackbox_exporter_daemon_dir: "{{ prometheus_blackbox_exporter_subdir }}"

- name: set download url for versions
  set_fact:
    prometheus_blackbox_exporter_tarball_url: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ prometheus_blackbox_exporter_version }}/blackbox_exporter-{{ prometheus_blackbox_exporter_version }}.{{ prometheus_platform_suffix }}.tar.gz"  # noqa 204

- name: create Prometheus group
  group:
    name: '{{ prometheus_blackbox_exporter_group }}'
    state: present

- name: create Prometheus user
  user:
    name: "{{ prometheus_blackbox_exporter_user }}"
    group: "{{ prometheus_blackbox_exporter_group }}"
    createhome: false
    shell: /sbin/nologin
    comment: "Prometheus User"
    state: present

- name: mkdir for prometheus and blackbox_exporter
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_blackbox_exporter_user }}"
    group: "{{ prometheus_blackbox_exporter_group }}"
    mode: 0750
  loop:
    - "{{ prometheus_blackbox_exporter_install_path }}"
    - "{{ prometheus_blackbox_exporter_config_path }}"

- name: download and untar blackbox_exporter tarball
  unarchive:
    src: "{{ prometheus_blackbox_exporter_tarball_url }}"
    dest: "{{ prometheus_blackbox_exporter_install_path }}"
    owner: '{{ prometheus_blackbox_exporter_user }}'
    group: '{{ prometheus_blackbox_exporter_group }}'
    copy: false
    creates: '{{ prometheus_blackbox_exporter_subdir }}'
  notify:
    - restart blackbox_exporter

- name: copy blackbox_exporter systemd profile
  template:
    src: 'blackbox_exporter.service.j2'
    dest: '/lib/systemd/system/blackbox_exporter.service'
    owner: root
    group: root
    mode: 0644
  notify:
    - systemd reload
    - restart blackbox_exporter

- name: copy blackbox_exporter config
  template:
    src: 'blackbox_exporter.defaults.j2'
    dest: '/etc/default/blackbox_exporter'
    owner: '{{ prometheus_blackbox_exporter_user }}'
    group: '{{ prometheus_blackbox_exporter_group }}'
    mode: 0640
  notify:
    - restart blackbox_exporter

- name: blackbox_exporter systemd service enable
  systemd:
    name: blackbox_exporter
    state: started
    enabled: true

...
