---

- name: install prometheus blackbox_exporter
  include_tasks: install.yaml
  tags:
    - prometheus
    - blackbox_exporter

- name: ufw | open access to blackbox_exporter
  include_tasks: ufw.yaml
  when: enable_ufw | bool
  tags:
    - prometheus
    - blackbox_exporter
    - ufw
...
